language: python

before_script:
  - pip install ansible coverage codecov

script:
  - coverage run --source=ansible_filter_hetzner -m unittest discover ansible_filter_hetzner/tests

deploy:
  provider: pypi
  user: nl2go
  password:
    secure: aeY97SP0aFt9guW1yVgb/Nf/DGhJoMAAylpCvbqS7Vd6v81lBW4ar0ZsZwcFxR6fG1bGBEkGusfWpx/UWxBEtW13wgV6+uRO8JsF0SCT85OBVoy7YcAx48k0fQxcossy/YRF/SXIjkRoyt3pkKWFDkq2hrl3Wk4aBBtI5aWwLE5Z0+e6Y/Q4dw/x5Stb72gXxHAXiy9y7OVpN/wjm605A6wHEhY0UUT8JudbqiXobPvw2XXz8JnXUK9djwl7lB9cs9FIrdp5KS1qHia9Ak1j4YKeax4qWu8WC84O8vBr+H+aDNTM2QYaRXIJVzAu4OwLNMmD0NnlaYjb7Nd/HDP/u9gf3pjuC69QaoWA4+Rdavq8WIpZuZUx1nG3K2KnBaHkpxdo2c1ByS6OrTL0xjooNQLCpMSy995JMzN8TmMWx7CLFLr/AFmZ8gZ+T8iGvcPto3ECxY0AsSzCS89s4PTk/CCYvv8ymp5pLs77Qo2BSAwZ2lXcm8LeG6hUO1YFlPM5dowYl2w5k5jYPGKYEE9zoaFCRb2CPs+c79naITkaxyovIiHDvraBA/9fiJpoBkokUauvjBZhuo0d424wuK4qyaDqKS2LG3kMDOg6BVHqhjDBVgvk/o/pci98PDPD8XzGffsQ1PM9uDkOfI2B26fRkuBFvQhAwCajs3L1Jlaou24=
  skip_cleanup: true
  on:
    tags: true

after_script:
  - codecov
