language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

before_script:
  - pip install ansible coverage codecov

script:
  - coverage run --source=ansible_filter -m unittest discover ansible_filter/tests

deploy:
  provider: pypi
  user: __token__
  password:
    secure: Nz6xBJxaDMn39LshvFrZ9B9I0sgtQxx0DybZ5CdHqDopHZ/4A5ed3S+qF7o8IPJBPV1n0fabgdpkhoaxQ8ONjyLkMc+yrexW2M2VAgMdsCSgxw8dbpUmA8hCO8EI/XMPodxdZEpU0BNPPGW19GRDPAjvObjR95EnZrfr1f8cclNSn2zuBuo3O8vn5rzwMX4DLQiOjUshWB7mzf1M7b71xiglVBGIh4P+gsGo/vPYdFF3+X/yvwqJa40SB6DE4FkGxbKgL9ZZrcCJ4tuAA1VQx+XftVRqVeZHKRTYi4cl4q899JF5k/wEWhr0QCpBU8U+yoBMMbK99KXCdNNUCxQOOI9cgIkxG26MKQrzozxLEnMWP2Ae0JURAbAW9KPT1bRf02EHNMDKRdIDIgA0aLDdCb05muPOhX0GYY+yRLgn13JWa4us0WkYHszDWL1k5OuXVtg4GfQCMh645NXFzQIJWyG5XrQXOa883dT5tzo51XhIYX8V+sJ6nvDnDT8HApScvNTw7088+s38z0rWY5ZIdUELw/ooGGVPaBJiuYWcPKomb9WTgdYP4lLYPBtsj85gNsdFI89Iisnmas9gitx2tbtmZTRdB/JFUsBi9vnTYuK5XcQODMPxHZ84ADT3jZELDR0S6i8eTBmmn76QpDKYptq4xPzdhvga3+i5i5Mw5L0=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true

after_script:
  - codecov
